//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGeeks.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PortunusEntitiesConnString : DbContext
    {
        public PortunusEntitiesConnString()
            : base("name=PortunusEntitiesConnString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Fragment> Fragments { get; set; }
        public virtual DbSet<Key> Keys { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ping> Pings { get; set; }
        public virtual DbSet<UserStatusCompact> UserStatusCompacts { get; set; }
    
        public virtual int CleanPingsForUser(Nullable<int> userFk)
        {
            var userFkParameter = userFk.HasValue ?
                new ObjectParameter("UserFk", userFk) :
                new ObjectParameter("UserFk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CleanPingsForUser", userFkParameter);
        }
    }
}
