//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGeeks.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatu
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string SourceIp { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
