//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGeeks.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKeyFragment
    {
        public int ID { get; set; }
        public int KeyID { get; set; }
        public int FragmentID { get; set; }
        public int OwnerID { get; set; }
        public int RecepientID { get; set; }
        public bool Recovered { get; set; }
    
        public virtual Fragment Fragment { get; set; }
        public virtual Key Key { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
