//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGeeks.API
{
    using System;
    using System.Collections.Generic;
    using Xamarin.Forms.Internals;

    [Preserve(AllMembers = true)]
    public partial class Contact
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ContactID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
