//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGeeks.API
{
    using System;
    using System.Collections.Generic;
    using Xamarin.Forms.Internals;

    [Preserve(AllMembers = true)]
    public partial class Setting
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Value { get; set; }
    }
}
